server:
  port: 8002
  error:
    include-message: always

spring:
  data:
    redis:
      host: 127.0.0.1
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org.myShortLink.admin: DEBUG
