dataSources:
  ds_0:
    username: root
    url: jdbc:mysql://localhost:3306/myShortLink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5

rules:
  - !SHARDING
    tables:
      t_user:
        actualDataNodes: ds_0.t_user_${0..15}
        tableStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: user_table_hash_mod
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
      t_group:
        actualDataNodes: ds_0.t_group_${0..15}
        tableStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: group_table_hash_mod
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake

    shardingAlgorithms:
      user_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      group_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16

    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 1

  - !ENCRYPT
    tables:
      t_user:
        columns:
          phone_number:
            cipherColumn: phone_number
            encryptorName: common_encryptor
        queryWithCipherColumn: true

    encryptors:
      common_encryptor:
        type: AES
        props:
          aes-key-value: ${ENCRYPTION_KEY}

props:
  sql-show: true